export {default as About} from "./About"
export {default as Competition} from "./Competition"
export {default as Contact} from "./Contact"
export {default as FAQ} from "./FAQ"
export {default as Landing} from "./Landing"
export {default as News} from "./News"